#!/bin/bash

# Copyright (c) 2013-2022, The PurpleI2P Project
#
# This file is part of Purple i2pd project and licensed under BSD3
#
# See full license text in LICENSE file at top of project tree

GITDESC=$(git describe --tags)

declare -A ABILIST=(
  ["armeabi-v7a"]="armv7l"
  ["arm64-v8a"]="aarch64"
  ["x86"]="x86"
  ["x86_64"]="x86_64"
)

# Remove old files and archives
if [ -d "archive" ]; then
  rm -r archive
fi

if [ -f "../i2pd_*_android_binary.zip" ]; then
  rm i2pd_*_android_binary.zip
fi

# Prepare files for package
mkdir archive

if [ ! -d "../../binary/libs/" ]; then
  echo "Prebuilt binaries folder is not found. Have you built them?"
  exit 1
fi

for ABI in "${!ABILIST[@]}"; do
  if [ -f "../../binary/libs/${ABI}/i2pd" ]; then
    cp ../../binary/libs/${ABI}/i2pd archive/i2pd-${ABILIST[$ABI]}
  fi
done

cp i2pd archive/i2pd
cp -rH ../../app/src/main/assets/certificates archive/
cp -rH ../../app/src/main/assets/tunnels.d archive/
cp -H ../../app/src/main/assets/i2pd.conf archive/
cp -H ../../app/src/main/assets/tunnels.conf archive/

# Compress files
cd archive
zip -r6 ../i2pd_${GITDESC}_android_binary.zip .

# Remove temporary folder
cd ..
rm -r archive
