[TelegramProxy-3443]
type = client
address = 127.0.0.1
port = 3443
destination = wzuvno5ism6wcwd3gurbchjrhxiiubq6b6yh7moiwk26btlc434q.b32.i2p
destinationport = 3443
keys = proxy-keys.dat
# This is the MTPROTO Telegram proxy.
# To connect to Telegram, click the link:
# https://t.me/proxy?server=127.0.0.1&port=3443&secret=311acfd614738aea7200813886ca2700
# If t.me is blocked, you can use this instead:
# tg://proxy?server=127.0.0.1&port=3443&secret=311acfd614738aea7200813886ca2700

[TelegramProxy-3444]
type = client
address = 127.0.0.1
port = 3444
destination = vxxfipsygx6jpz57pmb3d3mjgsk5ls2idxeo2bffs3yp62muyq7q.b32.i2p
destinationport = 443
keys = proxy-keys.dat
# This is the MTPROTO Telegram proxy.
# To connect to Telegram, click the link:
# https://t.me/proxy?server=127.0.0.1&port=3444&secret=d676d59cd211bfe0031e4db3debc6a1b
# If t.me is blocked, you can use this instead:
# tg://proxy?server=127.0.0.1&port=3444&secret=d676d59cd211bfe0031e4db3debc6a1b

[TelegramProxy-3445]
type = client
address = 127.0.0.1
port = 3445
destination = vp3vans4ra3vpo24orm5seaxvod4x4lwiqajrfazb62hfwb45ddq.b32.i2p
destinationport = 443
keys = proxy-keys.dat
# This is the MTPROTO Telegram proxy.
# To connect to Telegram, click the link:
# https://t.me/proxy?server=127.0.0.1&port=3445&secret=1b3e58008e4a2838505ea99838db21df
# If t.me is blocked, you can use this instead:
# tg://proxy?server=127.0.0.1&port=3445&secret=1b3e58008e4a2838505ea99838db21df

[TelegramProxy-3446]
type = client
address = 127.0.0.1
port = 3446
destination = ro2soroqdflozdibeehks5a4ftnlbpnjnkrcj5g7ci6ftu5jywja.b32.i2p
destinationport = 8443
keys = proxy-keys.dat
# This is the MTPROTO Telegram proxy.
# To connect to Telegram, click the link:
# https://t.me/proxy?server=127.0.0.1&port=3446&secret=ddd709f5c1209118117a859429efab2e87
# If t.me is blocked, you can use this instead:
# tg://proxy?server=127.0.0.1&port=3446&secret=ddd709f5c1209118117a859429efab2e87

[TelegramProxy-3447]
type = client
address = 127.0.0.1
port = 3447
destination = 2qzhdgjztbldasmjo5ek522kdruyhdo3izek5bjbl6rfnzauhzqa.b32.i2p
keys = proxy-keys.dat
# This is the MTPROTO Telegram proxy.
# To connect to Telegram, click the link:
# https://t.me/proxy?server=127.0.0.1&port=3447&secret=c5d1717f50bdab002e1ba52d9ed8f2fe
# If t.me is blocked, you can use this instead:
# tg://proxy?server=127.0.0.1&port=3447&secret=c5d1717f50bdab002e1ba52d9ed8f2fe

