name: Android CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Install rename tool
      run: |
        sudo apt-get update
        sudo apt-get install rename
    - name: Setup JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup Android SDK
      uses: maxim-lobanov/setup-android-tools@v1
      with:
        packages: |
          build-tools;29.0.3
          platforms;android-29
          ndk;21.4.7075529
        cache: true
    - name: Build required modules
      run: |
        export ANDROID_SDK_ROOT=$ANDROID_HOME
        export ANDROID_NDK_HOME=$ANDROID_HOME/ndk/21.4.7075529
        pushd app/jni
        ./build_boost.sh
        ./build_openssl.sh
        ./build_miniupnpc.sh
        popd
    - name: Build with Gradle
      run: ./gradlew --no-daemon assembleDebug
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        path: app/build/outputs/apk/debug/*.apk

