name: Android CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Install GNU C++ compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y g++
    - name: Switch to JDK 11
      run: export JAVA_HOME=$JAVA_HOME_11_X64
    - name: Install required Android SDK packages
      run: $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "cmake;3.22.1" "ndk;23.2.8568313"
    - name: Build required modules
      run: |
        export ANDROID_NDK_HOME=$ANDROID_HOME/ndk/23.2.8568313
        pushd binary/jni
        export BUILD_SO=1
        ./build_all.sh
        popd
    - name: Build with Gradle
      run: ./gradlew --no-daemon assembleDebug
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: android-apks
        path: app/build/outputs/apk/debug/*.apk

  build-binary:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Install GNU C++ compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y g++
    - name: Switch to JDK 11
      run: export JAVA_HOME=$JAVA_HOME_11_X64
    - name: Install required Android SDK packages
      run: $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "cmake;3.22.1" "ndk;23.2.8568313"
    - name: Build required modules
      run: |
        export ANDROID_NDK_HOME=$ANDROID_HOME/ndk/23.2.8568313
        pushd binary/jni
        ./build_all.sh
        popd
    - name: Build binaries with NDK
      run: |
        pushd binary/jni
        $ANDROID_NDK_HOME/ndk-build -j2 NDK_MODULE_PATH=$PWD
        popd
    - name: Create package with built binaries
      run: |
        pushd contrib/binary_pack
        ./build-archive
        popd
    - name: Upload binaries archive
      uses: actions/upload-artifact@v3
      with:
        name: android-binaries
        path: binary/libs/*
    - name: Upload binaries package
      uses: actions/upload-artifact@v3
      with:
        name: android-binaries-pack
        path: contrib/binary_pack/i2pd_*_android_binary.zip
